### ISSUE TITLE
Easy Fix: Word "lean" should be "learn "

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/git-version-control-introduction-to-version-control#4]
Under the "Identify Benefits" section.....Most people learn a few patterns...."   
Change "lean" to "learn" 

FYI...excellent writing - very clear. Much preferred over V6's explanation. Thanks, Flatiron!

************************TEXT HERE**********
And beyond these are even more advanced features that will help you optimize your workflow, once you master the basics. If that feels daunting, it's OK. Most people learn a few patterns of Git and never lean more until they absolutely have to. Over years they build up a rich set of techniques, but it's rare to find someone who knows everything about Git. You don't need to memorize every command and optional flag to get some of its best benefits.

**Comment by Sdcrouse** [comment]
I just submitted a pull request to them to fix that and a few other typos; I just hope I did it from the right location!

**Comment by drakeltheryuujin** [comment]
I updated the materials. Thanks for pointing out this mistake!
