### ISSUE TITLE
FSWD-Prework-2-0 Lessons out of order

### ISSUE THREAD

**Issue by PeteHanner** [learn-co-curriculum/git-version-control-introduction-to-version-control#8]
Please see the image link below. The revised prework lessons appear to be out of order. Git modules are reversed and at very end of curriculum. Programming mindset module comes after both Ruby modules. Environment setup is final module, etc.

[Image Link](https://i.imgur.com/Gmy8QGA.png)

**Comment by maxwellbenton** [comment]
Hi @PeteHanner,

Thank you for spotting this and providing feedback. We've corrected this issue so that Git: Getting and Adding to Code goes before Git Workflow. This change should be visible now in Learn's track menu.
